[Settings]
# Hash function to use (e.g., md5, sha1, sha256, sha384)
hash_function = sha384

# Size format mode:
# 1 = Display size in mixed units (e.g., 183 MB, 552 kB, 702 B)
# 2 = Display size as exact bytes (e.g., 192,455,358 B)
size_format = 1


###############################################################
#              Section for additional functions               #
#   The code was modular, and unnecesseary functions can be   #
#      disabled, like hashing, file size and edit time.       #
#                                                             #
#   Also, disabling hash function will speed up the process   #
#                                                             #
#                  Capitalizing is important                  #
###############################################################

edit_time_enable = True
size_enable = True
hash_enable = True